//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenGeeks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KitchenGeeks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Alarm {
            get {
                return ResourceManager.GetStream("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AppleTouchIcon {
            get {
                object obj = ResourceManager.GetObject("AppleTouchIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;&quot; /&gt;
        ///        &lt;title&gt;Lucius&apos;s Incident Logbook -- Log In&lt;/title&gt;
        ///        &lt;link href=&quot;Style.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///    A password is required in order to use this feature. Please enter the password below and hit Submit.&lt;br /&gt;&lt;br /&gt;
        ///    &lt;form method=&quot;post&quot; action=&quot;Login.htm&quot; name=&quot;Login&quot;&gt;
        ///        Password: &lt;input type=&quot;text&quot; name=&quot;P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;&quot; /&gt;
        ///        &lt;meta http-equiv=&quot;refresh&quot; content=&quot;1; url=&lt;!-- url --&gt;&quot;&gt; 
        ///        &lt;title&gt;Lucius&apos;s Incident Logbook -- Logged In&lt;/title&gt;
        ///        &lt;link href=&quot;Style.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///    Authenticated. Redirecting shortly...
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Authenticated {
            get {
                return ResourceManager.GetString("Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Updates&gt;
        ///  &lt;Update Version=&quot;0.2.1&quot;&gt;
        ///    &lt;![CDATA[* Added a Style.css file to the web server in order to make the mobile pages look correct on phones or tablets.
        ///* Fixed an error when right clicking in the player list (but not on a player) on the View Tournament screen could allow you to forfeit a blank player, causing a crash.
        ///* The web server should give a more helpful message when the port is in use or if you don&apos;t have permission to open the p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;&quot; /&gt;
        ///        &lt;title&gt;Lucius&apos;s Incident Logbook -- Rounds&lt;/title&gt;
        ///        &lt;link href=&quot;Style.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///        &lt;style&gt;
        ///            p.name
        ///            {
        ///                border-style: solid;
        ///                border-width: 3px;
        ///                text-align: center;
        ///            }
        ///
        ///            p.roundbordered
        ///            {
        ///                borde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChooseRound {
            get {
                return ResourceManager.GetString("ChooseRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;&quot; /&gt;
        ///        &lt;title&gt;Lucius&apos;s Incident Logbook -- Tournaments&lt;/title&gt;
        ///        &lt;link href=&quot;Style.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///        &lt;style&gt;
        ///            p {
        ///                border-style:solid;
        ///                border-width:3px;
        ///                text-align:center;
        ///                width: 100%;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChooseTournament {
            get {
                return ResourceManager.GetString("ChooseTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;&quot; /&gt;
        ///        &lt;title&gt;Lucius&apos;s Incident Logbook -- Edit Round&lt;/title&gt;
        ///        &lt;link href=&quot;Style.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///        &lt;style&gt;
        ///            p.round
        ///            {
        ///                border-style: solid;
        ///                border-width: 1px;
        ///                text-align: center;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;!-- error --&gt;Enter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditRound {
            get {
                return ResourceManager.GetString("EditRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lucius {
            get {
                object obj = ResourceManager.GetObject("Lucius", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LuciusIcon {
            get {
                object obj = ResourceManager.GetObject("LuciusIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OldScroll {
            get {
                object obj = ResourceManager.GetObject("OldScroll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;&quot; /&gt;
        ///        &lt;title&gt;Lucius&apos;s Incident Logbook -- Log In&lt;/title&gt;
        ///        &lt;link href=&quot;Style.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///    Invalid password provided. Please enter the password below and hit Submit.&lt;br /&gt;&lt;br /&gt;
        ///    &lt;form method=&quot;post&quot; action=&quot;Login.htm&quot; name=&quot;Login&quot;&gt;
        ///        Password: &lt;input type=&quot;text&quot; name=&quot;Password&quot; maxlength=&quot;30&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetryAuthenticate {
            get {
                return ResourceManager.GetString("RetryAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///    font-size: 1em;
        ///}.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///        &lt;meta http-equiv=&quot;refresh&quot; content=&quot;1; url=&lt;!-- url --&gt;&quot;&gt; 
        ///        &lt;title&gt;Lucius&apos;s Incident Logbook -- Logged In&lt;/title&gt;
        ///        &lt;link href=&quot;Style.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///	&lt;/head&gt;
        ///    &lt;body&gt;
        ///    &lt;!-- message --&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
    }
}
